### ISSUE TITLE
Apple Auth can't sign in 

### ISSUE THREAD

**Issue by Perklone** [Pengabdi-Tjoean/SLAP-Sounds-Like-A-Plan#78]
causes: Unknown
tested with iPhone 14 iOS 16.0

ketika login ada masalah dimana gk bisa login dan gk bisa masuk ke HomeViewController, hasil google nunjukkin kalo terjadi beberapa kali ke orang lain tapi solusinya belom jelas.

![image](https://user-images.githubusercontent.com/71255973/205011026-d948b82f-628f-4c8d-8f60-0c46e502819d.png)

**Comment by gremlinflat** [comment]
flexing ip 14 ini mah

**Comment by gremlinflat** [comment]
fixed on main branch
