### ISSUE TITLE
Constraint warning on event tab (gradient label)

### ISSUE THREAD

**Issue by gremlinflat** [Pengabdi-Tjoean/SLAP-Sounds-Like-A-Plan#86]
<img width="614" alt="Screenshot 2022-12-10 at 12 07 56 AM" src="https://user-images.githubusercontent.com/25357458/206754428-59f62d5b-1b19-4cf0-8542-3d7c5e6380da.png">
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2809368a0 V:[Hayo.SLAPGradientLabel:0x104813fd0]-(19)-[Hayo.SLAPTextField:0x114833000]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by Perklone** [comment]
file apa ini

**Comment by gremlinflat** [comment]
InsertInvitationCodeViewController.swift line 16
-----
    let titleLabel = SLAPGradientLabel(text: "Have an Invitation code already?")
-----

**Comment by Perklone** [comment]
#90
