### ISSUE TITLE
Join by code character limitation

### ISSUE THREAD

**Issue by gremlinflat** [Pengabdi-Tjoean/SLAP-Sounds-Like-A-Plan#87]
![IMG_AC8E8ED33239-1](https://user-images.githubusercontent.com/25357458/206755207-e93e607c-3b99-4a1d-91a2-d5c2f3cba246.jpeg)

should be: input < 6

**Comment by gremlinflat** [comment]
+ join button isn't disabled

**Comment by Perklone** [comment]
#89
