### ISSUE TITLE
Bottom popup sheet darkmode 

### ISSUE THREAD

**Issue by gremlinflat** [Pengabdi-Tjoean/SLAP-Sounds-Like-A-Plan#93]
![IMG_D0A8C6FFF6A3-1](https://user-images.githubusercontent.com/25357458/206897455-e47e8a7b-078c-4b80-b8fe-0eb59bdf94ab.jpeg)

uilabel & container

**Comment by gremlinflat** [comment]
![IMG_722F9D086D60-1](https://user-images.githubusercontent.com/25357458/206900833-4a13b042-0fcd-404a-97f8-0b2e07d78e30.jpeg)

scroll view bottom padding is too small

**Comment by jasonskycore** [comment]
fixed![image](https://user-images.githubusercontent.com/92720717/206926731-4363a241-8f0a-4baa-9886-78182064957c.png)
